language: python
env:
- DB=pgsql
- DB=mysql
- DB=sqlite
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
install:
- pip install -U setuptools tox tox-travis
before_script:
- sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test;' -U postgres;
  psql -c 'create database test;' -U postgres; export DBURI='postgresql+psycopg2://postgres@localhost/test';
  fi"
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS test';
  export DBURI='mysql+mysqldb://test@localhost/test?charset=utf8'; fi"
- sh -c "if [ '$DB' = 'sqlite' ]; then export DBURI='sqlite:///%(here)s/test.sqlite';
  fi"
script: tox
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: adamhadani
  password:
    secure: Lylx+2lisa4KPZBqXDcA6Kxf2WN7t1QjK/XBhbQdNM29Dt7CZysLD4cnZQnIiECRP6CP/34OP8KrzjUbB9a1AIgI4k20yXtRY/7l9WvQrHuFG0xNsAWhboM5ZFieJi9u1o+fr6MlqZcnNVV8ouwfJTwIlpLMOkEXxDgp8z3BBCjC3ykB35VyQs1crMDezloyTVcY6XaZxs9mMDBbykL1GScwl4a1pOVgqrvlnfwuhM663NbrkySSjLqzE/seBu/a058SO4nB7kE1UCPx6NQ4WwUGLkcu7bTWNJFOlIQzh5Va3NBmnq6WdGrLgxCQ3OSkW5cvX+qZAklUFsLS23tzT8yc0MsS9LOeTbPuVsa7eEsgNzwwkZT2Wwg56qEcM+lGtV8f5TKvBmPsEdTzGSQTPHjRRNBko8HhLSGFSWkpPDXlvygXsX7sorPWhOstN/fYmj1beTAQWfpwjIWtqaS3qgTDrZvdTmACj6iCD1e/SjY8RpwIbM1fXS+qYcB+YzNQzCliIgv2Qh6xDbgqXBJiBudCmgGgYtngW2Df/NjWQrBYAkEHFHjl1twJu7m+ra8xT+MMULyIlaoF7G0550C0oZxsYh8kmYDvOW7NMyVnKWeAYzU1uEBjBtq24zmx/6iB45RAQdbYFSEArRi58kQf6feEeqohWhHCjg6054YCAQQ=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
    branch: develop
