# http://travis-ci.org/#!/gjhiggins/rdflib-sqlalchemy
language: python
env:
    - DB=pgsql
    - DB=mysql
    - DB=sqlite
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - pip install -U setuptools tox tox-travis
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test;' -U postgres; psql -c 'create database test;' -U postgres; export DBURI='postgresql+psycopg2://postgres@localhost/test'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS test'; export DBURI='mysql+mysqldb://test@localhost/test?charset=utf8'; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then export DBURI='sqlite:///%(here)s/test.sqlite'; fi"
script: tox
