# http://travis-ci.org/#!/gjhiggins/rdflib-sqlalchemy
language: python
branches:
  only:
    - master
    - idkey
env:
    - DB=pgsql
    - DB=mysql
    - DB=sqlite
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
install:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then pip install -r requirements-py2.txt --use-mirrors; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then pip install -r requirements-py3.txt --use-mirrors; fi
    - python setup.py install
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test;' -U postgres; psql -c 'create database test;' -U postgres; export DBURI='postgresql+psycopg2://postgres@localhost/test'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS test'; export DBURI='mysql+mysqldb://test@localhost/test?charset=utf8'; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then export DBURI='sqlite:///%(here)s/test.sqlite'; fi"
script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then PYTHONWARNINGS=default nosetests --with-coverage --cover-tests --cover-package=rdflib_sqlalchemy ; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then PYTHONWARNINGS=default nosetests --with-coverage --cover-tests --cover-package=build/src/rdflib_sqlalchemy --where=./build/src; fi

